language: ruby
bundler_args: --without development
before_script:
  - psql -c 'create database kosynierzy_test;' -U postgres
  - cp config/database.example.yml config/database.yml
  - ./bin/rake db:schema:load
services:
  - redis-server
script:
  - bundle exec rake spec
rvm:
  - "2.2.1"
notifications:
  email:
    - github@kosynierzy.info
addons:
  hosts:
    - account.kosynierzy.dev
