language: ruby
sudo: false
cache: bundler
bundler_args: --without development
before_script:
  - psql -c 'create database kosynierzy_test;' -U postgres
  - cp config/database.example.yml config/database.yml
  - ./bin/rake db:schema:load
services:
  - redis-server
script:
  - bundle exec brakeman -z
  - bundle exec rake spec
rvm:
  - "2.0.0"
env:
  - HOST: account.kosynierzy.dev
notifications:
  email:
    - github@kosynierzy.info
addons:
  hosts:
    - account.kosynierzy.dev
