development:
  adapter: postgresql
  encoding: unicode
  database: kosynierzy_development
  pool: 5
  username: kosynierzy
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: kosynierzy_test
  pool: 5
  username: kosynierzy
  password:
